[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
FRONTEND_URL = "https://www.mdmcmusicads.com"
CORS_ORIGIN = "https://www.mdmcmusicads.com"
VITE_API_URL = "https://mdmcv4-backend-production-b615.up.railway.app/api/v1" 